name: Build and deploy to GitHub pages
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run check
      - run: npm run lint
      - run: npm run build
      - run: npm run signed-release
      - run: npm run generate-update-manifest
        env:
          WEB_EXT_API_KEY: ${{ secrets.MOZILLA_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.MOZILLA_API_SECRET }}
      - uses: actions/upload-pages-artifact@v2
        with:
          path: web-ext-artifacts
  deploy:
    needs: release
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2